[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dno-fno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "carbs @ git+https://github.com/imbue-ai/carbs.git ; python_full_version >= '3.11'",
    "h5py>=3.14.0",
    "flax>=0.11 ; python_full_version >= '3.11' and sys_platform == 'linux'",
    "jax[cuda12]>=0.7 ; python_full_version >= '3.11' and sys_platform == 'linux'",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "optax>=0.2.5 ; python_full_version >= '3.11' and sys_platform == 'linux'",
    "scipy>=1.13.1",
    "tqdm>=4.67.3",
    "pypdf>=6.9.2",
    "orbax-checkpoint>=0.11.6 ; python_full_version >= '3.11' and sys_platform == 'linux'",
    "ruff>=0.15.10",
]

[tool.setuptools]
packages = ["solver", "solver.solvers", "solver.data", "solver.tanaka_ICs", "solver.peregrine", "solver.gen_data", "solver.gen_data.pipeline", "solver.evals", "fno_jax"]

[tool.setuptools.package-dir]
fno_jax = "models/fno-jax"
